config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
}
  root to: "top#index"
  resources :pictures, only: [:index, :new, :create, :edit, :update, :destroy]

  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # >>>>>>ここから
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # =====ここまでを追記
    # 省略
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :title, :content, :photo_image,presence: true
  belongs_to :user
  mount_uploader :photo_image, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  has_many :pictures

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :authenticate_user!
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
      @picture = Picture.new(pictures_params)
      @picture.user_id = current_user.id
      if @picture.save
        redirect_to pictures_path, notice: "写真を作成しました！"
        NoticeMailer.sendmail_picture(@picture).deliver
      else
        render  'new'
      end
    end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update(pictures_params)
    redirect_to pictures_path, notice: "写真を更新しました！"
  else
    render 'new'
  end

  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path, notice: "写真を削除しました！"
  end

  private
    def pictures_params
      params.require(:picture).permit(:title, :content, :photo_image)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def twitter
   # You need to implement the method below in your model
   @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

   if @user.persisted?
     set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
     sign_in_and_redirect @user, event: :authentication
   else
     session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
     redirect_to new_user_registration_url
   end
 end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end
module ActionView
  module Helpers
    module FormHelper
      def error_messages!(object_name, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if !resource || resource.errors.empty?

        messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

        html = <<-HTML
          <div class="alert alert-danger">
            <ul>#{messages}</ul>
          </div>
        HTML

        html.html_safe
      end
      
      def error_css(object_name, method, options = {})
        resource = self.instance_variable_get("@#{object_name}")
        return '' if resource.errors.empty?

        resource.errors.include?(method) ? 'has-error' : ''
      end
    end

    class FormBuilder
      def error_messages!(options = {})
        @template.error_messages!(@object_name, options.merge(object: @object))
      end

      def error_css(method, options = {})
        @template.error_css(@object_name, method, options.merge(object: @object))
      end
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogenic</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<!-- ここから追加 -->
<%= form_for(@picture, html: {multipart: true}) do |f| %>
<!-- ここまで追加 -->

<%= f.error_messages! %>


<!-- ここから追加 -->
  <div class="field">
    <%= f.label :photo_image %>
    <%= f.file_field :photo_image %>
  </div>
<!--ここまで追加-->

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
	<div class="row header">
		<div class="col-xl-6 left_nav">
			<h1>insta9</h1>
        <form class="submit">
           <input type="text" />
           <button type="button" class="btn active disabled btn-info">
				   送信
			    </button>
        </form>
		</div>
		<div class="col-xl-6 right_nav" >
			<ul>
        <% if user_signed_in? %>
        <li><%= link_to '投稿一覧', pictures_path %></li>
        <li><%= link_to '投稿', new_picture_path %></li>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
			</ul>
		</div>
	</div>
	</div>
</div>
<div class="container">
  <div class="col-md-6 col-md-offset-4 col-sm-10 col-sm-offset-1">
<h2>写真を編集する</h2>
<%= render 'form' %>
</div>
</div>

app/views/pictures/index.html.erb
<head>
    <meta charset="UTF-8">
    <title>Achieve</title>
    <link rel="stylesheet" href="normalize.css">
    <link rel="stylesheet" href="style.css">
</head>
<div class="container-fluid">
	<div class="row header">
		<div class="col-xl-6 left_nav">
			<h1>insta9</h1>
        <form class="submit">
           <input type="text" />
           <button type="button" class="btn active disabled btn-info">
				   送信
			    </button>
        </form>
		</div>
		<div class="col-xl-6 right_nav" >
			<ul>
        <% if user_signed_in? %>
        <li><%= link_to '投稿一覧', pictures_path %></li>
        <li><%= link_to '投稿', new_picture_path %></li>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
			</ul>
		</div>
	</div>
	</div>
</div>
<div class="container">
  <div class="wrapper col-lg-10 col-lg-offset-4 col-sm-10">
    <p><%= notice %></p>
    <h1>写真一覧</h1>
          <%= link_to "写真を作成する", new_picture_path, class: 'btn btn-default' %>

<% @pictures.each do |picture| %>
<div class="row">
  <h4><strong><%= picture.title %></strong></h4>
  <p>本文:<%= picture.content %></p>
  <p>写真:<%= image_tag picture.photo_image %></p>
  <p><%= picture.user_id %></p>
  <%= link_to "写真を編集する", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-success' %>
　<%= link_to '写真を削除する', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
</div>
<% end %>

</div>
</div>

app/views/pictures/new.html.erb
<p id="notice"><%= notice %></p><div class="container-fluid">
	<div class="row header">
		<div class="col-xl-6 left_nav">
			<h1>insta9</h1>
        <form class="submit">
           <input type="text" />
           <button type="button" class="btn active disabled btn-info">
				   送信
			    </button>
        </form>
		</div>
		<div class="col-xl-6 right_nav" >
			<ul>
        <% if user_signed_in? %>
        <li><%= link_to '投稿一覧', pictures_path %></li>
        <li><%= link_to '投稿', new_picture_path %></li>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
			</ul>
		</div>
	</div>
	</div>
</div>
<div class="container">
  <div class="col-md-6 col-md-offset-4 col-sm-10 col-sm-offset-1">
<h2>写真を作成する</h2>
<%= render 'form' %>
</div>
</div>

app/views/top/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Insta9</title>
    <link rel="stylesheet" href="stylesheet.css">
</head>
<body>
<div class="container-fluid">
	<div class="row header">
		<div class="col-xl-6 left_nav">
			<h1>insta9</h1>
        <form class="submit">
           <input type="text" />
           <button type="button" class="btn active disabled btn-info">
				   送信
			    </button>
        </form>
		</div>
		<div class="col-xl-6 right_nav" >
			<ul>
        <% if user_signed_in? %>
        <li><%= link_to '投稿一覧', pictures_path %></li>
        <li><%= link_to '投稿', new_picture_path %></li>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
			</ul>
		</div>
	</div>
	</div>
  <section class="main-header">
  <p class="flash"><%= notice %><%= alert %></p>
  </section>
</div>